### ISSUE TITLE
[Cypress] Update UI e2e tests to make it green again

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#218]
After latest fixes that allow e2e to run again in STD UI we need to update them to bring them back again.

For instance, from these errors: https://github.com/epinio/epinio-end-to-end-tests/runs/8200088219?check_suite_focus=true#step:14:258 we need to update the app check for routing name:

```
     AssertionError: Timed out retrying after 10000ms: Expected to find content: '/https:\/\/testapp-[a-z0-9]{5}.10.162.231.184.omg.howdoi.website/' but never did.
      at Context.eval (https://epinio.10.162.231.184.omg.howdoi.website/__cypress/tests?p=cypress/support/index.ts:3109:27)
```

**Comment by mmartin24** [comment]
Issues about suffixes fixed here: https://github.com/epinio/epinio-end-to-end-tests/pull/219
I have to continue with the rest.

Summary of what is left before release changes: https://github.com/epinio/epinio-end-to-end-tests/runs/8205147984?check_suite_focus=true

#### configuration-tests:
```
  1) Configuration testing
       Create an application with a configuration, unbind the configuration and delete all:
     AssertionError: Timed out retrying after 10000ms: expected '<tr.main-row>' to contain '1/1'
      at Context.eval (https://epinio.10.162.231.184.omg.howdoi.website/__cypress/tests?p=cypress/support/index.ts:3300:25)

  2) Configuration testing
       Bind a created configuration to an existing application, edit configuration and delete all:
     CypressError: `cy.click()` failed because this element is detached from the DOM.
```
#### application-tests:

```
  1) Applications testing
       Create mysql service, bind it to a Wordpress app and push it:
     AssertionError: Timed out retrying after 120000ms: Expected to find content: 'GitHub' but never did.
      at Context.eval (https://epinio.10.162.231.183.omg.howdoi.website/__cypress/tests?p=cypress/support/index.ts:2930:12)
```

**Comment by mmartin24** [comment]
Taking a look at the errors, I think it is better to apply fixes after release. Config test 1 seems to have still a but of slowness waiting for the amount of replicas to go down. This was fixed, but it does not seem to be reflected here. Also to check this in the latest UI I had to do a UI locator update.  Second config occurs because we do not have a cleansing mechanism for apps yet there, so if first test fails, it persists for second; that can be updated. Application testing also tries to check for a new element in source type (Github) which does not appear in the current UI yet. So I will wait until release is done to check directly on new version.

**Comment by mmartin24** [comment]
After some adjustments all tests seem green again in this branch: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3033634860 with the exception of the Github source type. For some reason it returns always a 403 response right after typing the repo. This does not happen locally, only in CI:
![image](https://user-images.githubusercontent.com/37271841/189586922-3c75c83f-070f-492b-9eaf-3d45403b6f13.png)
I will try to troubleshoot further, but one possibility may be to keep this test disabled until we can find a solution meanwhile the rest are green
